### ISSUE TITLE
failed to provision volume with StorageClass "seaweedfs-storage": rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by venuvvp** [seaweedfs/seaweedfs-csi-driver#10]
Hello Team,

I am facing the following error while trying to create a a persistant volume claim:

=======================
  Type     Reason                Age                    From                                                                                  Message
  ----     ------                ----                   ----                                                                                  -------
  Warning  ProvisioningFailed    12m (x17 over 58m)     seaweedfs-csi-driver_csi-seaweedfs-controller-0_ed15a103-cb2f-47af-ac9d-fa2bbd7b5294  failed to provision volume with StorageClass "seaweedfs-storage": rpc error: code = DeadlineExceeded desc = context deadline exceeded

  Normal   ExternalProvisioning  3m45s (x222 over 59m)  persistentvolume-controller                                                           waiting for a volume to be created, either by external provisioner "seaweedfs-csi-driver" or manually created by system administrator

  Normal   Provisioning          2m29s (x19 over 59m)   seaweedfs-csi-driver_csi-seaweedfs-controller-0_ed15a103-cb2f-47af-ac9d-fa2bbd7b5294  External provisioner is provisioning volume for claim "default/seaweedfs-csi-pvc"

=======================

Here is the output of the kubectl describe pvc:
========================
# kubectl describe pvc
Name:          seaweedfs-csi-pvc
Namespace:     default
StorageClass:  seaweedfs-storage
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: seaweedfs-csi-driver
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                From                                                                                  Message
  ----     ------                ----               ----                                                                                  -------
  Normal   Provisioning          16s (x5 over 71s)  seaweedfs-csi-driver_csi-seaweedfs-controller-0_ed15a103-cb2f-47af-ac9d-fa2bbd7b5294  External provisioner is provisioning volume for claim "default/seaweedfs-csi-pvc"
  Normal   ExternalProvisioning  11s (x5 over 71s)  persistentvolume-controller                                                           waiting for a volume to be created, either by external provisioner "seaweedfs-csi-driver" or manually created by system administrator
  Warning  ProvisioningFailed    6s (x5 over 61s)   seaweedfs-csi-driver_csi-seaweedfs-controller-0_ed15a103-cb2f-47af-ac9d-fa2bbd7b5294  failed to provision volume with StorageClass "seaweedfs-storage": rpc error: code = DeadlineExceeded desc = context deadline exceeded
root@master:~/seaweedfs-csi-driver# 
root@master:~/seaweedfs-csi-driver# 
root@master:~/seaweedfs-csi-driver# kubectl describe pvc
Name:          seaweedfs-csi-pvc
Namespace:     default
StorageClass:  seaweedfs-storage
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: seaweedfs-csi-driver
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                    From                                                                                  Message
  ----     ------                ----                   ----                                                                                  -------
  Warning  ProvisioningFailed    12m (x17 over 58m)     seaweedfs-csi-driver_csi-seaweedfs-controller-0_ed15a103-cb2f-47af-ac9d-fa2bbd7b5294  failed to provision volume with StorageClass "seaweedfs-storage": rpc error: code = DeadlineExceeded desc = context deadline exceeded

  Normal   ExternalProvisioning  3m45s (x222 over 59m)  persistentvolume-controller                                                           waiting for a volume to be created, either by external provisioner "seaweedfs-csi-driver" or manually created by system administrator

  Normal   Provisioning          2m29s (x19 over 59m)   seaweedfs-csi-driver_csi-seaweedfs-controller-0_ed15a103-cb2f-47af-ac9d-fa2bbd7b5294  External provisioner is provisioning volume for claim "default/seaweedfs-csi-pvc"

========================

Could you please help me with this?

Thank you

**Comment by chrislusf** [comment]
The error is not helpful. Need to see the logs of the pods.

**Comment by venuvvp** [comment]
[csi_provisoner_logs.txt](https://github.com/seaweedfs/seaweedfs-csi-driver/files/5802044/csi_provisoner_logs.txt)
[csi_driver_registrar.txt](https://github.com/seaweedfs/seaweedfs-csi-driver/files/5802045/csi_driver_registrar.txt)
[csi_attacher_logs.txt](https://github.com/seaweedfs/seaweedfs-csi-driver/files/5802046/csi_attacher_logs.txt)
[seaweedfs-csi-plugin_logs.txt](https://github.com/seaweedfs/seaweedfs-csi-driver/files/5802048/seaweedfs-csi-plugin_logs.txt)

Thank you for your reply @chrislusf . I have attached the logs from the pods.

**Comment by chrislusf** [comment]
what is the PVC yaml? Is it same as the `deploy/kubernetes/sample-seaweedfs-pvc.yaml`?

**Comment by chrislusf** [comment]
Also, what is your kubernetes version? Try to upgrade first.

**Comment by chrislusf** [comment]
make sure the `seaweedfs-csi.yaml` has the correct SEAWEEDFS_FILER value in 2 places.

**Comment by venuvvp** [comment]
> what is the PVC yaml? Is it same as the `deploy/kubernetes/sample-seaweedfs-pvc.yaml`?

yes @chrislusf , I am using the same yaml file to create pvc.


> Also, what is your kubernetes version? Try to upgrade first.

version is 1.20.1
=================
Client Version: v1.20.1
Server Version: v1.20.1
=================

> make sure the `seaweedfs-csi.yaml` has the correct SEAWEEDFS_FILER value in 2 places.

Yes, I put the Seaweedfs master's IP in both the places. I tried Seaweedfs master's public IP, internal IP and localhost (both seaweedfs and k8s masters are in same host) but no luck so far.

**Comment by chrislusf** [comment]
Need to use filer address, not master address.

**Comment by venuvvp** [comment]
I started the filer and everything working fine.

Thank you @chrislusf

**Comment by chrislusf** [comment]
thanks for the update!
