### ISSUE TITLE
Update helm chart version

### ISSUE THREAD

**Issue by rohitchormale** [seaweedfs/seaweedfs-csi-driver#106]
I can see the changes in helm chart of seaweedfs-csi-driver but version is not bumped up yet - https://github.com/seaweedfs/seaweedfs-csi-driver/blob/master/deploy/helm/seaweedfs-csi-driver/Chart.yaml#L5

Hope this is not intentional or am I missing something ?

**Comment by chrislusf** [comment]
updated. Thanks!
