### ISSUE TITLE
Resizing a PVC not resizing its filesystem when different Pods mount it

### ISSUE THREAD

**Issue by bohrshaw** [seaweedfs/seaweedfs-csi-driver#107]
Steps to reproduce:
1. Pod A mounts a PVC of size 1G.
2. Resize the PVC to 2G.
3. Delete Pod A.
4. Create Pod B with this PVC mounted.
5. Resize the PVC to 3G.
6. Restart Pod B. (The filesystem in the PVC also expanded.)
7. Delete Pod B.
8. Recreate Pod A with this PVC mounted.

Now the mounted filesystem in Pod A is still 1G, which is not expected.

**Comment by chrislusf** [comment]
This is expected. There are no limit on the storage size. The size info is not stored on the storage server side.
