### ISSUE TITLE
Behaviour of seaweedfs-csi-driver with 2 clusters

### ISSUE THREAD

**Issue by rohitchormale** [seaweedfs/seaweedfs-csi-driver#124]
I have a kubernetes setup where 2 seaweedfs clusters are installed in same namespace. Seaweedfs-csi-driver is pointed to only one cluster but I am noticing sometimes `system input/output` errors. This never happend with single cluster. So my question is - will seaweedfs-cs-driver work properly in this setup ? Is there any possible conflict I should check ?

**Comment by chrislusf** [comment]
no clue. need to reproduce and debug.

**Comment by rohitchormale** [comment]
@chrislusf  thanks for the reply. I will try to get you steps soon. More details on setup - 
Basically I have a bare git repos on seaweedfs and I am mouting seaweedfs on multiple pods via csi driver. 
On few pods, few files from git objects are missing. These are very small files. If I run `git fsck`, I can see `unable to mmap ./objects00/blah-blah-blah no such file or directory. object currupt or missing`.  I am just wondering why those are missing only from few pods, not from all. And is there a way to sync them again ?  
Restarting pods solves my problem but that is not option always.

**Comment by rohitchormale** [comment]
It turns out having 2 clusters has nothing to do with our issue. It looks like issue was happening because of slow initial syncing. After inserting some delay in out operations, it got resolved.
