### ISSUE TITLE
CSI driver only supports gRPC

### ISSUE THREAD

**Issue by optix2000** [seaweedfs/seaweedfs-csi-driver#13]
CSI driver is hard-coded to _only_ use gRPC and will make no attempt to fall back to HTTP and there is no option use the HTTP port.

This is mostly confusing because you're expected to pass the HTTP port to the driver, but it uses the gRPC port internally. If gRPC is intended to be the only protocol, then it would make more sense to pass the gRPC instead of the HTTP port to be less confusing. (ie easier to understand what firewall/security group holes to open, easier for auditors, etc).

https://github.com/seaweedfs/seaweedfs-csi-driver/blob/e5bc351871e6447f0b54e79e4b0356d3aed57bed/cmd/seaweedfs-csi-driver/main.go#L14
https://github.com/seaweedfs/seaweedfs-csi-driver/blob/e5bc351871e6447f0b54e79e4b0356d3aed57bed/pkg/driver/driver.go#L128

It also prints that it's connecting to `:8888` when in reality it's connecting to `:18888`, adding to the confusion
https://github.com/seaweedfs/seaweedfs-csi-driver/blob/e4cb2a5c428bebb73ed7e067f2ad16484639b0ac/cmd/seaweedfs-csi-driver/main.go#L34

```
% ss -np | grep seaweedfs-csi
u_str  ESTAB  0       0        //var/lib/csi/sockets/pluginproxy/csi.sock 85739                   * 85738      users:(("seaweedfs-csi-d",pid=11238,fd=9))
u_str  ESTAB  0       0        //var/lib/csi/sockets/pluginproxy/csi.sock 85706                   * 85705      users:(("seaweedfs-csi-d",pid=11238,fd=8))
u_str  ESTAB  0       0        //var/lib/csi/sockets/pluginproxy/csi.sock 85759                   * 85758      users:(("seaweedfs-csi-d",pid=11238,fd=10))
tcp    ESTAB  0       0                                         10.42.0.8:52164       10.43.169.119:18888      users:(("seaweedfs-csi-d",pid=11238,fd=11))
```

Ideally it should either auto-detect what protocol to use, or give a flag/option to specify a protocol to use. If it's expected to _only_ use gRPC, then all the configs should use the gRPC port.

**Comment by chrislusf** [comment]
Having multiple ways to configure filer is confusing.

**Comment by optix2000** [comment]
Sure, but again this is unintuitive. I think it's fine if you only want to support gRPC, but then the configs should be explicitly set to use gRPC as the port number.

You're specifying the HTTP port (`:8888`), but the driver _actually_ uses the gRPC port (`:18888`). There's no documentation saying that the driver will not actually use the configured port of `:8888`. Unless you dive into the code, you have no way of knowing what the actual port being used is.
