### ISSUE TITLE
seaweedfs-csi-driver is filling disk in /tmp

### ISSUE THREAD

**Issue by philpep** [seaweedfs/seaweedfs-csi-driver#20]
Hi, I just tested the kubernetes deployment (not helm chart) and it seems seaweedfs-csi-driver container is writting a lot of "leveldb" files in /tmp (inside the container) during usage, until the disk is full actually.

It's weird to have data here no ?

Many thanks for seaweedfs, it looks very promising!

**Comment by chrislusf** [comment]
Those files are for data caching.

We can add an option to configure it to some other directory.

**Comment by philpep** [comment]
Thanks for reply! There's a maximum size limit ? Can this be configured ?

**Comment by chrislusf** [comment]
max cache size?

**Comment by philpep** [comment]
Thanks a lot!
