### ISSUE TITLE
PersistentVolumeClaim stays Pending on   unknown service filer_pb.SeaweedFiler

### ISSUE THREAD

**Issue by arthurlogilab** [seaweedfs/seaweedfs-csi-driver#29]
While trying to deploy the seaweedfs operator https://github.com/seaweedfs/seaweedfs-operator and this csi-driver to use it, I get a pending PersistentVolumeClaim with the following error : 

```
failed to provision volume with StorageClass "seaweedfs-storage": rpc error: code = Unknown desc = Error setting bucket metadata: mkdir /buckets/pvc-d7f94d12-88f2-408e-84f2-c7c41da8a6aa: CreateEntry: rpc error: code = Unimplemented desc = unknown service filer_pb.SeaweedFiler
```

Installed it with helm as follows :  

```
helm install --set seaweedfsFiler='seaweed1-master:9333' seaweedfs-csi-driver  .
```

Hoping this would pick up the seaweed1-master Service deployed by the operator. Am I missing something ?

**Comment by chrislusf** [comment]
> helm install --set seaweedfsFiler='seaweed1-master:9333' seaweedfs-csi-driver  .

`seaweed1-master:9333` is master, not filer.
