### ISSUE TITLE
Timed out waiting for the condition when attaching volumes

### ISSUE THREAD

**Issue by rellax-net** [seaweedfs/seaweedfs-csi-driver#3]
Hi, I have a strange error when using the csi-driver. The PVC are provisionned without problems but when trying to attach them to a pod, there are errors saying:

**1)Unable to attach or mount volumes: unmounted volumes=[redacted], unattached volumes=[redacted]: timed out waiting for the condition
2)MountVolume.SetUp failed for volume "pvc-13e343e1-9eee-4c15-a3d0-75ee751145ce" : rpc error: code = DeadlineExceeded desc = context deadline exceeded**

Then after a few minutes, the pvc attach succesfully to the pods. I tried with RWO, RWX with different pods, it always shows these two errors before attaching successfully to the pods. Any idea what might happens here?
Thanks

**Comment by chrislusf** [comment]
Added a fix. Please check it now.

**Comment by rellax-net** [comment]
Thanks, I'll check is as soon as possible and I'll get back to you.

**Comment by rellax-net** [comment]
YES, that did it, Thanks a lot.
