### ISSUE TITLE
Cant configure multiple filer addresses?

### ISSUE THREAD

**Issue by lilibin-0618** [seaweedfs/seaweedfs-csi-driver#41]
When I configure multiple filer addresses, creating pvc will report an error.

        - name: seaweedfs-csi-plugin
          image: harbor.bruce.com/library/seaweedfs-csi-driver:v2.0.1 
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--filer=$(SEAWEEDFS_FILER)"
            - "--nodeid=$(NODE_ID)"
            - "--cacheCapacityMB=$(SEAWEEDFS_CACHE_CAPACITY_MB)"
            - "--cacheDir=$(SEAWEEDFS_CACHE_DIR)"
            - "--map.uid=$(SEAWEEDFS_MAP_UID)"
            - "--map.gid=$(SEAWEEDFS_MAP_GID)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: SEAWEEDFS_FILER
              value: "10.17.100.28:8888,10.17.100.29:8888,10.17.100.30:8888" # host and port of your SeaweedFs filer
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

then show error like this and pvc pending

  Warning  ProvisioningFailed    3s (x8 over 2m10s)    seaweedfs-csi-driver_csi-seaweedfs-controller-0_85f0363c-0b0d-49c3-ae9e-1e1a766d20d5  failed to provision volume with StorageClass "seaweedfs-storage": rpc error: code = Unknown desc = Error setting bucket metadata: mkdir /buckets/pvc-7c57fcfe-ed42-4325-b893-f3408e78fb79: CreateEntry: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup 10.17.100.28:8888,10.17.100.29:8888,10.17.100.30: no such host"

**Comment by lilibin-0618** [comment]
Why closed?

**Comment by chrislusf** [comment]
fixed

**Comment by skurfuerst** [comment]
@chrislusf Awesome :) Could you publish a new release? Thanks ❤️ ❤️

**Comment by chrislusf** [comment]
released. Please let me know whether it works for you.

**Comment by skurfuerst** [comment]
Thanks, awesome, will do ❤️
