### ISSUE TITLE
Disproportional storage use of volumes related to reserved pvc size

### ISSUE THREAD

**Issue by peedy2495** [seaweedfs/seaweedfs-csi-driver#45]
Volumesize: 30GB (default, MaxVolumeSizeMb not set)
I reserved in k8s 5Gi for pcv via seaweedfs-csi-driver.
2x6 Volumes has been reserved for an 5Gi pvc -> without replication 180Gi (!) -> is it the same behaviour of bucket reservation as S3-Storage (SeaweedFS wiki)? ... or is it a Bug?

**Comment by chrislusf** [comment]
You can configure the volume size to be smaller.

**Comment by peedy2495** [comment]
Is it possible to change the volume size in an existing cluster?

**Comment by chrislusf** [comment]
Yes. See "weed master -h"
