### ISSUE TITLE
In csi-seaweedfs-ndoe a lot of disk space is used

### ISSUE THREAD

**Issue by EasonHe** [seaweedfs/seaweedfs-csi-driver#47]
/ # ls
bin                   etc                   media                 proc                  sbin                  sys                   var
csi                   home                  mnt                   root                  seaweedfs-csi-driver  tmp
dev                   lib                   opt                   run                   srv                   usr
/ # du -sh /tmp/
69.3G   /tmp/
/ # ls  /tmp
00ca21b8                                                                    seaweedfs-csi-driver.ali-hb2-test-app12.root.log.INFO.20220210-014334.1
0edd4f9e                                                                    seaweedfs-csi-driver.ali-hb2-test-app12.root.log.WARNING.20220217-073615.1
0ef27a39                                                                    weed.INFO
0f2b3b92                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-073420.12
101d077e                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-073420.13
14485655                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-074138.36
1518a5a3                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-074139.47
16dfbc77                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-080836.61
1c8c0c09                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-080836.71
29c3b724                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-081254.86
2ac0c984                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-081255.97
315a8a5d                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-081815.112
33bc4104                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-081816.123
36889796                                                                    weed.ali-hb2-test-app12.root.log.INFO.20220217-082125.137
3ab78d09

**Comment by chrislusf** [comment]
Need to rotate the log files in the glog library.

**Comment by chrislusf** [comment]
Added a fix to log to stderr only.
