### ISSUE TITLE
 Limit the pvc capacity and isolate the multi-tenant directory

### ISSUE THREAD

**Issue by aland-zhang** [seaweedfs/seaweedfs-csi-driver#48]
How does the pvc provided by the k8s csi plugin limit the capacity and isolate the multi-tenant directory? These two requirements are just needed.

**Comment by chrislusf** [comment]
The isolated directory is fixed in https://github.com/chrislusf/seaweedfs/commit/fcf371444356b98d7f1c169068ee2a890889c122

**Comment by aland-zhang** [comment]
pvc capacity limit I think I can refer to the method of S3 Bucket Quota to limit the capacity

**Comment by chrislusf** [comment]
Added quota support.
