### ISSUE TITLE
filer high availability

### ISSUE THREAD

**Issue by EasonHe** [seaweedfs/seaweedfs-csi-driver#49]
The filer server only writes one address in the configuration
Does it support multiple addresses?
filer server  can't achieve real high availability. If the connected node is disconnected, the storage used will also be disconnected and cannot be reconnected. I have to restart my application

**Comment by chrislusf** [comment]
“in the configuration” in which configuration?

**Comment by chrislusf** [comment]
You can pass in comma separated filer list.
