### ISSUE TITLE
`weed mount` logs can't be read

### ISSUE THREAD

**Issue by airhorns** [seaweedfs/seaweedfs-csi-driver#5]
I'm struggling a bit to get volumes in my k8s cluster working properly, and I am sure it is something I have done wrong, but debugging it is difficult because I can't see what `weed mount` might be reporting as an issue, but I can see the CSI attacher running it. Would there be anything wrong with forwarding the logs from the managed `weed mount` command to the stdout/err of the CSI components running it to assist with debugging?

**Comment by chrislusf** [comment]
>
>
> weed mount command to the stdout/err?
>

Already logging to the stdout

>

**Comment by airhorns** [comment]
Ah, I took a look through the code and didn't see where it would be doing that, but maybe my Go-fu is just not strong enough. Right now when I try to write to a file on a CSI-mounted seaweed volume the process trying to write hangs indefinitely. I can create files with `touch` just fine which I think means the filer and FUSE mount are working, but writing any bytes to files causes the writing process to go unresponsive, and doesn't seem to log anything on the filer, on the volume servers, or on any of the `csi-seaweedfs-node` DaemonSet pods. Does the verbosity have to be upped from the default to get the log entries maybe?

**Comment by chrislusf** [comment]
seems filer is not able to connect to the volume servers.

increase the log level by running `weed -v=4 filer ...`.

There should be some printouts. Do you at least see some outputs when starting filer/volume/mount?

you can share your yaml files?

**Comment by airhorns** [comment]
Ah, bumping up the verbosity helped, found a `No free volumes left!` message, and bumped up the max volumes from the default helm chart output and all is working now. Sorry for the red herring!
