### ISSUE TITLE
Feature request: define disktype for volume via storageclass

### ISSUE THREAD

**Issue by dimm0** [seaweedfs/seaweedfs-csi-driver#50]
It's now possible to define the disk type a folder should be placed in using https://github.com/chrislusf/seaweedfs/wiki/Path-Specific-Configuration#options

Can we extend this to the PVC storageClass, so that users can choose which device type they want when creating the volume?

**Comment by chrislusf** [comment]
should be doable with `weed mount -disk=xxx` option. The change will be similar to https://github.com/seaweedfs/seaweedfs-csi-driver/commit/76c7b84418c4c99141c1ffbde2ac2060b2620e1d

**Comment by dimm0** [comment]
Sorry :) noW, not "noT"

**Comment by chrislusf** [comment]
@dimm0 I have made the required code change. 

However, I am not so sure about PersistentVolume or StorageClass changes. Please help to test it out.

**Comment by chrislusf** [comment]
fs.configure is to dynamically detect the disk type.

this fix just specify the disk type explicitly. No need to change fs.configure.
