### ISSUE TITLE
can't write data

### ISSUE THREAD

**Issue by AliKhadivi** [seaweedfs/seaweedfs-csi-driver#88]
Hi
I install seaweedfs-csi.
Then, create below pod and pvc.
**my pvc:** https://github.com/seaweedfs/seaweedfs-csi-driver/blob/master/deploy/kubernetes/sample-seaweedfs-pvc.yaml
**my pod:** https://github.com/seaweedfs/seaweedfs-csi-driver/blob/master/deploy/kubernetes/sample-busybox-pod.yaml
I can't write data in `/data`, but can create empty file.
![image](https://user-images.githubusercontent.com/74895885/190178710-46e74a05-e01e-44bb-ae1e-2fb43090a056.png)

**Comment by csi-driver-bug** [comment]
Same issue on version 3.32
When i copy a file from other directory to pvc directory, it report: **Input/output error**

And i try to upload a file by WEBDAV to this PVC directory (RWX)
filer log report:
**E1020 19:07:46.180020 filer_server_handlers_write.go:47 failing to assign a file id: rpc error: code = Unknown desc = no free volumes left for {"collection":"pvc-cb7e8663-337a-4761-9092-6fa6acf361a5","replication":{"rack":1},"ttl":{"Count":0,"Unit":0}}
E1020 19:07:46.180074 filer_server_handlers_write_upload.go:209 upload error: rpc error: code = Unknown desc = no free volumes left for {"collection":"pvc-cb7e8663-337a-4761-9092-6fa6acf361a5","replication":{"rack":1},"ttl":{"Count":0,"Unit":0}}
E1020 19:07:47.046046 filer_server_handlers_write.go:47 failing to assign a file id: rpc error: code = Unknown desc = no free volumes left for {"collection":"pvc-cb7e8663-337a-4761-9092-6fa6acf361a5","replication":{"rack":1},"ttl":{"Count":0,"Unit":0}}
E1020 19:07:47.046102 filer_server_handlers_write_upload.go:209 upload error: rpc error: code = Unknown desc = no free volumes left for {"collection":"pvc-cb7e8663-337a-4761-9092-6fa6acf361a5","replication":{"rack":1},"ttl":{"Count":0,"Unit":0}}
I1020 19:07:47.046163 common.go:70 response method:POST URL:/buckets/pvc-cb7e8663-337a-4761-9092-6fa6acf361a5/ with httpStatus:500 and JSON:{"error":"rpc error: code = Unknown desc = no free volumes left for {\"collection\":\"pvc-cb7e8663-337a-4761-9092-6fa6acf361a5\",\"replication\":{\"rack\":1},\"ttl\":{\"Count\":0,\"Unit\":0}}"}**

**Comment by chrislusf** [comment]
see https://github.com/seaweedfs/seaweedfs/wiki/S3-API-FAQ#can-not-upload-due-to-no-free-volumes-left

Need to allocate more volumes.

**Comment by csi-driver-bug** [comment]
> see https://github.com/seaweedfs/seaweedfs/wiki/S3-API-FAQ#can-not-upload-due-to-no-free-volumes-left
> 
> Need to allocate more volumes.

volumes is sufficient
i can write data to other DIR like /buckets/xxxx/，(same filer and volume server)
only DIR which create by csi-dirver can not write either in the pod or outside pod

**Comment by csi-driver-bug** [comment]
i mount a RWX DIR to the pod
and i can wirte the same data by fuse mount, but can not write by csi-dirver

[root@filer]# df -h
...
localhost:8888:/  938G   26G  912G   3% /fuse
...
[root@filer]# echo abc123 > /fuse/test/a.txt


[root@filer]# kubectl exec -it nginx -- /bin/bash
root@nginx:/# df -h
...
x.x.x.x:8888:/test  938G     0  938G   0% /data
...
root@nginx:/# cat /data/a.txt
abc123
root@nginx:/# echo 111 > /data/a.txt
root@nginx:/# ls -l /data/a.txt
-rw-r--r--+ 1 1000 1000 0 Oct 21 01:54 /data/a.txt

**Comment by chrislusf** [comment]
https://github.com/seaweedfs/seaweedfs/wiki/FAQ#how-many-volumes-do-i-need

**Comment by rohitchormale** [comment]
@chrislusf I am facing similar issue. I have allocated too many volumes but problem persists. As mentioned by @AliKhadivi, this issue is specific to volumes mounted by CSI only. Files are getting created but can't read/write. I can do successful read/write via fuse mount in same setup but not using CSI. 
 
 @AliKhadivi have you found any work around for this ?

**Comment by AliKhadivi** [comment]
@rohitchormale No, I did not find

**Comment by rohitchormale** [comment]
@AliKhadivi ok mine just resolved. You should check logs from csi driver if not already (something like `kubectl logs -f -n kube-system daemonset.apps/seaweedfs-csi-driver-node -c seaweedfs-csi-plugin` etc )
